# ansible/playbooks/microk8s/workers.yml - Updated
---
- name: Join workers to MicroK8s cluster
  hosts: workers
  become_user: "{{ ansible_user }}"
  
  tasks:
    - name: Read join command from local file
      set_fact:
        join_command: "{{ lookup('file', '/tmp/microk8s_join_command') }}"
      delegate_to: localhost
      run_once: true
      
    - name: Check if node is already part of cluster
      shell: sg microk8s -c "microk8s kubectl get nodes"
      register: cluster_nodes
      failed_when: false
      delegate_to: "{{ groups['control_plane'][0] }}"
      
    - name: Join worker to cluster
      shell: "sg microk8s -c '{{ join_command }} --worker'"
      when: ansible_hostname not in cluster_nodes.stdout
      timeout: 300
      register: join_result
      
    - name: Display join result
      debug:
        msg: |
          Node: {{ inventory_hostname }} ({{ region }})
          Join Status: {{ 'Already joined' if ansible_hostname in cluster_nodes.stdout else 'Joined successfully' }}
          
    - name: Wait for node to be ready
      shell: sg microk8s -c "microk8s status --wait-ready"
      timeout: 300