# ansible/inventories/azure/hosts.yml - Updated for same-region setup
all:
  vars:
    ansible_user: azureuser
    ansible_ssh_private_key_file: ~/.ssh/azure_rsa
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
    ansible_python_interpreter: /usr/bin/python3
    ansible_connection_timeout: 30
    ansible_command_timeout: 300
       
  children:
    microk8s_cluster:
      children:
        control_plane:
          hosts:
            control-plane:
              ansible_host: 4.210.149.226
              private_ip: 10.0.1.4
              microk8s_role: primary
              region: west_europe
                       
        workers:
          hosts:
            worker-1:
              ansible_host: 104.47.147.204
              private_ip: 10.0.2.4
              microk8s_role: worker
              region: west_europe