# ansible/playbooks/site.yml - Simplified for same-region setup
---
- name: Deploy MicroK8s Infrastructure
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Display deployment info
      debug:
        msg: |
          🚀 Starting MicroK8s Deployment:

          Control Plane: {{ groups['control_plane'][0] }} ({{ hostvars[groups['control_plane'][0]]['ansible_host'] }})
          Workers: {{ groups['workers'] | join(', ') }}

          Total Nodes: {{ groups['microk8s_cluster'] | length }}

# Phase 1: Clean installation on all nodes
- import_playbook: microk8s/clean-install.yml

# Phase 2: Setup control plane with addons
- import_playbook: microk8s/control-plane.yml

# Phase 3: Join workers to cluster (same VNet - easy!)
- import_playbook: microk8s/workers.yml

# Phase 4: Install GitOps tools
- import_playbook: jenkins/install.yml

# Phase 5: Install ArgoCD
- import_playbook: argocd/install.yml

# Phase 6: Verify cluster
- name: Verify Cluster
  hosts: control_plane
  become_user: "{{ ansible_user }}"
  tasks:
    - name: Get all cluster nodes
      shell: sg microk8s -c "microk8s kubectl get nodes -o wide"
      register: final_cluster_status

    - name: Get all pods
      shell: sg microk8s -c "microk8s kubectl get pods -A"
      register: all_pods

    - name: Display final cluster status
      debug:
        msg: |
          🎉 MicroK8s Cluster Ready!

          === NODES ===
          {{ final_cluster_status.stdout }}

          === SYSTEM PODS ===
          {{ all_pods.stdout }}

          === ACCESS INFO ===
          Control Plane: {{ ansible_host }}
          kubectl access: ssh -i ~/.ssh/azure_rsa azureuser@{{ ansible_host }}

          === GITOPS TOOLS ===
          Jenkins: http://{{ ansible_host }}:30080
          ArgoCD: https://{{ ansible_host }}:30443

          === NEXT STEPS ===
          1. Configure Jenkins credentials
          2. Set up the GitOps repository
          3. Create a Jenkins pipeline for SimpleEshop
